### ISSUE TITLE
WebClient not working with Firefox browser

### ISSUE THREAD

**Issue by lexesv** [TeaSpeak/TeaSpeak-Web#3]
## System Information  
***Browser***:  Firefox/60.0
***Operating System*** (Linux|Windows|Mac):  Linux (Debian 9)
  
## Details  
***Issue type***:
- [*] Javascript
- [ ] Style
- [ ] System / backend
- [ ] Unknown  
  
## Issue  
Not working.

![image](https://user-images.githubusercontent.com/15149258/38766383-22441756-3fda-11e8-98ec-283174e5c165.png)

**Comment by WolverinDEV** [comment]
Fixed, working now :)
