### ISSUE TITLE
missing files ? 

### ISSUE THREAD

**Issue by lemignon** [TeaSpeak/TeaSpeak-Web#6]
## System Information  
***Browser***:  
***Operating System*** (Linux|Windows|Mac):  
  
## Details  
***Issue type*** (Javascript | Style | System / backend | Other | Unknown):
  
## Issue  
***Reason for reporting this issue***:  
  
***Detailed Description***:  
  
Failed to load resource: the server responded with a status of 404 (Not Found)
2load.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
loader.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)

***Steps to reproduce***:  
Load page
  
  
  
*Delete me: If you dont follow this issue template, you may not get a response or the issue get instandly closed.*

**Comment by WolverinDEV** [comment]
As I already said within my other post, 
This is the project behind TeaSpeak web, and not a ready to install mirror.
You have to build the project to 'execute' it
