### ISSUE TITLE
tutorial ? 

### ISSUE THREAD

**Issue by lemignon** [TeaSpeak/TeaSpeak-Web#7]
## System Information  
***Browser***:  Chrome
***Operating System*** (Linux|Windows|Mac):  Windows
  
## Details  
***Issue type*** (Javascript | Style | System / backend | Other | Unknown):
  
## Issue  
***Reason for reporting this issue***:  

Is there a tutorial to setting up the teaweb ? 
  
***Detailed Description***:  
  
***Steps to reproduce***:  
  
  
  
*Delete me: If you dont follow this issue template, you may not get a response or the issue get instandly closed.*

**Comment by WolverinDEV** [comment]
This is just the repro for web.teaspeak.de
Also a own mirror isn't really recommended, cause the users could give you some critical data, like the forum account or the ts3 identity

**Comment by lemignon** [comment]
Hum , we don't want your forum Auth but we could add our own website auth . 

I want my webclient on my own domain. I prefer to pay a licence to have teaweb on my own domain .  

If i can't get it on my own domain i am simply going to continue to use discord wich is 1000 x better than everything and more secure at all. 

"or the ts3 identity"

You think it's better for us to give to you our ts3 identity ... ?

**Comment by WolverinDEV** [comment]
Its not possible to create a own auth system.
The TS3 Identity and Forum Identity auth system is enforced.

You could easily use an IFrame or stuff like that :)

Yep, but i stay with the name TeaSpeak and TeaWeb for the promise, that all TS3 identity data is just local on the web browser. But if you host the side by your self, you could easaly use some javascript to transfere the data to your server.
