### ISSUE TITLE
detect output device.

### ISSUE THREAD

**Issue by lemignon** [TeaSpeak/TeaSpeak-Web#8]
## System Information  
***Browser***:  chrome
***Operating System*** (Linux|Windows|Mac):   Windows
  
## Details  
***Issue type*** (Javascript | Style | System / backend | Other | Unknown):
  
## Issue  
***Reason for reporting this issue***:  
   I can't hear anything
***Detailed Description***:  
  I can't hear anything  on webclient . Only microphone seems to works. 
i am using USB headphones.
***Steps to reproduce***:  
- 
  
  
  
*Delete me: If you dont follow this issue template, you may not get a response or the issue get instandly closed.*

**Comment by WolverinDEV** [comment]
Sad news:
Its not possible to select the destination device via web.

**Comment by gthgame** [comment]
strange because my usb heeadphone is the default device at all ;(
